// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3j6oKD5ttKilFp6uHnjeDb7Qnjo5RJI',
    appId: '1:445975755519:web:fe382601d9dcd254212aca',
    messagingSenderId: '445975755519',
    projectId: 'kes1-323bb',
    authDomain: 'kes1-323bb.firebaseapp.com',
    storageBucket: 'kes1-323bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTyOHYBmBFHEtKR_xod0VSA0ZyDcyufU',
    appId: '1:445975755519:android:9408010be27d82f2212aca',
    messagingSenderId: '445975755519',
    projectId: 'kes1-323bb',
    storageBucket: 'kes1-323bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO2L74eoQ0wer-gGVkCS9MuqzClJH85_s',
    appId: '1:445975755519:ios:de4aab3dc8b29d4b212aca',
    messagingSenderId: '445975755519',
    projectId: 'kes1-323bb',
    storageBucket: 'kes1-323bb.appspot.com',
    iosBundleId: 'com.example.ap4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO2L74eoQ0wer-gGVkCS9MuqzClJH85_s',
    appId: '1:445975755519:ios:de4aab3dc8b29d4b212aca',
    messagingSenderId: '445975755519',
    projectId: 'kes1-323bb',
    storageBucket: 'kes1-323bb.appspot.com',
    iosBundleId: 'com.example.ap4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3j6oKD5ttKilFp6uHnjeDb7Qnjo5RJI',
    appId: '1:445975755519:web:c951f54c6d7dc808212aca',
    messagingSenderId: '445975755519',
    projectId: 'kes1-323bb',
    authDomain: 'kes1-323bb.firebaseapp.com',
    storageBucket: 'kes1-323bb.appspot.com',
  );
}
